/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeizoenRouteImport } from './routes/seizoen'
import { Route as PerceelkaartRouteImport } from './routes/perceelkaart'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RijRijIdRouteImport } from './routes/rij.$rijId'
import { Route as RijRijIdPlantenRouteImport } from './routes/rij.$rijId.planten'
import { Route as RijRijIdObservatieRouteImport } from './routes/rij.$rijId.observatie'
import { Route as RijRijIdMetingRouteImport } from './routes/rij.$rijId.meting'
import { Route as RijRijIdFenologieRouteImport } from './routes/rij.$rijId.fenologie'

const SeizoenRoute = SeizoenRouteImport.update({
  id: '/seizoen',
  path: '/seizoen',
  getParentRoute: () => rootRouteImport,
} as any)
const PerceelkaartRoute = PerceelkaartRouteImport.update({
  id: '/perceelkaart',
  path: '/perceelkaart',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RijRijIdRoute = RijRijIdRouteImport.update({
  id: '/rij/$rijId',
  path: '/rij/$rijId',
  getParentRoute: () => rootRouteImport,
} as any)
const RijRijIdPlantenRoute = RijRijIdPlantenRouteImport.update({
  id: '/planten',
  path: '/planten',
  getParentRoute: () => RijRijIdRoute,
} as any)
const RijRijIdObservatieRoute = RijRijIdObservatieRouteImport.update({
  id: '/observatie',
  path: '/observatie',
  getParentRoute: () => RijRijIdRoute,
} as any)
const RijRijIdMetingRoute = RijRijIdMetingRouteImport.update({
  id: '/meting',
  path: '/meting',
  getParentRoute: () => RijRijIdRoute,
} as any)
const RijRijIdFenologieRoute = RijRijIdFenologieRouteImport.update({
  id: '/fenologie',
  path: '/fenologie',
  getParentRoute: () => RijRijIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instellingen': typeof InstellingenRoute
  '/perceelkaart': typeof PerceelkaartRoute
  '/seizoen': typeof SeizoenRoute
  '/rij/$rijId': typeof RijRijIdRouteWithChildren
  '/rij/$rijId/fenologie': typeof RijRijIdFenologieRoute
  '/rij/$rijId/meting': typeof RijRijIdMetingRoute
  '/rij/$rijId/observatie': typeof RijRijIdObservatieRoute
  '/rij/$rijId/planten': typeof RijRijIdPlantenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instellingen': typeof InstellingenRoute
  '/perceelkaart': typeof PerceelkaartRoute
  '/seizoen': typeof SeizoenRoute
  '/rij/$rijId': typeof RijRijIdRouteWithChildren
  '/rij/$rijId/fenologie': typeof RijRijIdFenologieRoute
  '/rij/$rijId/meting': typeof RijRijIdMetingRoute
  '/rij/$rijId/observatie': typeof RijRijIdObservatieRoute
  '/rij/$rijId/planten': typeof RijRijIdPlantenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instellingen': typeof InstellingenRoute
  '/perceelkaart': typeof PerceelkaartRoute
  '/seizoen': typeof SeizoenRoute
  '/rij/$rijId': typeof RijRijIdRouteWithChildren
  '/rij/$rijId/fenologie': typeof RijRijIdFenologieRoute
  '/rij/$rijId/meting': typeof RijRijIdMetingRoute
  '/rij/$rijId/observatie': typeof RijRijIdObservatieRoute
  '/rij/$rijId/planten': typeof RijRijIdPlantenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/instellingen'
    | '/perceelkaart'
    | '/seizoen'
    | '/rij/$rijId'
    | '/rij/$rijId/fenologie'
    | '/rij/$rijId/meting'
    | '/rij/$rijId/observatie'
    | '/rij/$rijId/planten'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/instellingen'
    | '/perceelkaart'
    | '/seizoen'
    | '/rij/$rijId'
    | '/rij/$rijId/fenologie'
    | '/rij/$rijId/meting'
    | '/rij/$rijId/observatie'
    | '/rij/$rijId/planten'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/instellingen'
    | '/perceelkaart'
    | '/seizoen'
    | '/rij/$rijId'
    | '/rij/$rijId/fenologie'
    | '/rij/$rijId/meting'
    | '/rij/$rijId/observatie'
    | '/rij/$rijId/planten'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InstellingenRoute: typeof InstellingenRoute
  PerceelkaartRoute: typeof PerceelkaartRoute
  SeizoenRoute: typeof SeizoenRoute
  RijRijIdRoute: typeof RijRijIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seizoen': {
      id: '/seizoen'
      path: '/seizoen'
      fullPath: '/seizoen'
      preLoaderRoute: typeof SeizoenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perceelkaart': {
      id: '/perceelkaart'
      path: '/perceelkaart'
      fullPath: '/perceelkaart'
      preLoaderRoute: typeof PerceelkaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rij/$rijId': {
      id: '/rij/$rijId'
      path: '/rij/$rijId'
      fullPath: '/rij/$rijId'
      preLoaderRoute: typeof RijRijIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rij/$rijId/planten': {
      id: '/rij/$rijId/planten'
      path: '/planten'
      fullPath: '/rij/$rijId/planten'
      preLoaderRoute: typeof RijRijIdPlantenRouteImport
      parentRoute: typeof RijRijIdRoute
    }
    '/rij/$rijId/observatie': {
      id: '/rij/$rijId/observatie'
      path: '/observatie'
      fullPath: '/rij/$rijId/observatie'
      preLoaderRoute: typeof RijRijIdObservatieRouteImport
      parentRoute: typeof RijRijIdRoute
    }
    '/rij/$rijId/meting': {
      id: '/rij/$rijId/meting'
      path: '/meting'
      fullPath: '/rij/$rijId/meting'
      preLoaderRoute: typeof RijRijIdMetingRouteImport
      parentRoute: typeof RijRijIdRoute
    }
    '/rij/$rijId/fenologie': {
      id: '/rij/$rijId/fenologie'
      path: '/fenologie'
      fullPath: '/rij/$rijId/fenologie'
      preLoaderRoute: typeof RijRijIdFenologieRouteImport
      parentRoute: typeof RijRijIdRoute
    }
  }
}

interface RijRijIdRouteChildren {
  RijRijIdFenologieRoute: typeof RijRijIdFenologieRoute
  RijRijIdMetingRoute: typeof RijRijIdMetingRoute
  RijRijIdObservatieRoute: typeof RijRijIdObservatieRoute
  RijRijIdPlantenRoute: typeof RijRijIdPlantenRoute
}

const RijRijIdRouteChildren: RijRijIdRouteChildren = {
  RijRijIdFenologieRoute: RijRijIdFenologieRoute,
  RijRijIdMetingRoute: RijRijIdMetingRoute,
  RijRijIdObservatieRoute: RijRijIdObservatieRoute,
  RijRijIdPlantenRoute: RijRijIdPlantenRoute,
}

const RijRijIdRouteWithChildren = RijRijIdRoute._addFileChildren(
  RijRijIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InstellingenRoute: InstellingenRoute,
  PerceelkaartRoute: PerceelkaartRoute,
  SeizoenRoute: SeizoenRoute,
  RijRijIdRoute: RijRijIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
